### PR TITLE
Fix paths and synchronize instructions of git and non-git repos

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by davedash** [comment]
Please rebase your commits into a smaller set of commits, some of these seem to do things, and then undo things (like the fix path commits)

git rebase --interactive master

is a good interface for this, you can mark commits as "f" or "s" to squash, or simply fold into previous commits.

**Comment by glogiotatidis** [comment]
Thanks for the rebase tip. Indeed I committed wrong documentation, which was fixed with a newer commit. 

Now everything should be better, except this "Merge commit" which I can't figure a way not to push to you or delete. Any ideas?

**Comment by davedash** [comment]
Also, you may want to talk about https://github.com/jbalogh/vending-machine/ - no worries if I'm asking a lot, this is definitely an improvement as is, but I think talking about using the `vend` command will make it 10x.

**Comment by glogiotatidis** [comment]
Aha! I'll have a look at this and make the appropriate additions.

**Pull request closed without merging**
